GET http://localhost:3000/journalistRoute

###

POST http://localhost:3000/journalistRoute
Content-Type: application/json

{
    "name": "João Coiso",
    "job_function": "Faz cenas",
    "date_of_admission": 11112011,
    "birthday" : 11111911,
    "email" : "joaocoiso@gmail.com"
}

###

PATCH http://localhost:3000/journalistRoute/:journalistID
Content-Type: application/json

{
    "name": "Jonas Pistolas"    
}

# Trocar :journalistID pelo ID do jornalista que quisermos fazer o patch

###

DELETE http://localhost:3000/journalistRoute/:journalistID

# Trocar :journalistID pelo ID do jornalista que quisermos fazer o delete

###




GET http://localhost:3000/locationRoute

###

POST http://localhost:3000/locationRoute
Content-Type: application/json

{
    "adress": "Rua do Tal Sitio, nº 201, Camarate",
    "floor": 4,
    "phonenumber" : 21913465 
}

###

PATCH http://localhost:3000/locationRoute/:locationID
Content-Type: application/json

{
    "adress": "Outro Sitio"    
}

# Trocar :locationID pelo ID do jornalista que quisermos fazer o patch

###

DELETE http://localhost:3000/locationRoute/:locationID

# Trocar :locationID pelo ID do jornalista que quisermos fazer o delete

###



GET http://localhost:3000/sectionRoute

###

POST http://localhost:3000/sectionRoute
Content-Type: application/json

{
    "name":"Secção",
    "reports_on": "Descritivo",
    "number_of_workers": 4,
    "alloted_parking_space" : 0,
    "section_email" : "tribuna@example.com"  
}

###

PATCH http://localhost:3000/sectionRoute/:sectionID
Content-Type: application/json

{
    "name": "Outro Nome"    
}

# Trocar :locationID pelo ID do jornalista que quisermos fazer o patch

###

DELETE http://localhost:3000/sectionRoute/:sectionID

# Trocar :locationID pelo ID do jornalista que quisermos fazer o delete

###